#!/usr/bin/env python3
"""Render recorded Luvus graphics frames in a private Xvfb + real Kitty window.

First run test-remote-sessions.py --graphics-only. Then, on Linux:
  uv run --with pillow scripts/test-kitty-graphics-visual.py <fixture> <kitty>

Kitty is a test dependency, not installed or launched in a user's display.
Records are generated by real isolated Luvus clients, not synthetic images.
An independent renderer preflight is explicitly separate from these records;
append --renderer-only to diagnose Xvfb/OpenGL/Kitty before testing Luvus.
Requires Xvfb plus a working software OpenGL 3.1+ driver. The screenshots prove
visibility, updates, clipping and cleanup, not physical-macOS font geometry.
"""
import json
import os
from pathlib import Path
import select
import signal
import subprocess
import sys
import tempfile
import time


REPO = Path(__file__).resolve().parent.parent


def fixture_path(value):
    root = Path(value).resolve()
    assert root.parent == REPO / "target", root
    assert (root / ".isolated-smoke").read_text() == str(root), root
    return root


def replay(root, recording, title):
    import fcntl
    import struct
    import termios
    import tty
    home = Path(os.environ["HOME"]).resolve()
    assert home.is_relative_to(root), home
    rows, columns, width, height = struct.unpack(
        "HHHH", fcntl.ioctl(0, termios.TIOCGWINSZ, b"\0" * 8))
    (home / "geometry.json").write_text(json.dumps({
        "rows": rows, "columns": columns, "width": width, "height": height,
        "cell_width": width // columns if columns else 0,
        "cell_height": height // rows if rows else 0,
    }))
    tty.setraw(0)
    assert recording.parent == root
    if recording.name == "__renderer-probe__":
        # Independent renderer preflight, not evidence of Luvus correctness.
        # A solid red image expanded over Unicode virtual placements proves
        # the display/driver can render the exact primitive used by Luvus.
        marks = "\u0305\u030d\u030e\u0310\u0312\u033d\u033e\u033f\u0346\u034a\u034b\u034c\u0350\u0351\u0352\u0357"
        wire = "\x1b[2J\x1b_Ga=t,t=d,i=7,f=24,s=8,v=8,q=2;" + "/wAA" * 64 + "\x1b\\"
        wire += "\x1b_Ga=p,U=1,i=7,q=2,c=16,r=8;\x1b\\\x1b[38;2;0;0;7m"
        for row in range(8):
            wire += f"\x1b[{row + 3};30H"
            wire += "".join("\U0010eeee" + marks[row] + marks[col] for col in range(16))
        data = memoryview((wire + "\x1b[0m").encode())
    else:
        assert recording.suffix == ".ansi"
        data = memoryview(recording.read_bytes())
    assert len(data) <= 64 * 1024 * 1024
    while data:
        data = data[os.write(1, data):]
    # A title receipt proves Kitty consumed the entire recorded stream. It
    # does not alter text, images, placement or clipping in that stream.
    os.write(1, ("\x1b]2;" + title + "\x07").encode())
    while True:
        signal.pause()


def stop(process):
    if process is None or process.poll() is not None:
        return
    process.terminate()
    try:
        process.wait(timeout=5)
    except subprocess.TimeoutExpired:
        process.kill()
        process.wait(timeout=5)


def safe_windows(receipt):
    # Kitty's full ls result includes its inherited environment. Retain only
    # viewport identity/geometry; never persist unrelated caller credentials.
    return [{"id": window["id"], "platform_window_id": window["platform_window_id"],
             "tabs": [{"windows": [{key: child[key] for key in
                                    ("id", "title", "columns", "lines") if key in child}
                                   for child in tab["windows"]]}
                      for tab in window["tabs"]]}
            for window in json.loads(receipt)]


def main():
    if len(sys.argv) > 1 and sys.argv[1] == "--replay":
        root = fixture_path(sys.argv[2])
        replay(root, (root / sys.argv[3]).resolve(), sys.argv[4])
        return

    from PIL import ImageGrab, features
    assert features.check("xcb"), "Pillow must support X11 screenshots"
    root = fixture_path(sys.argv[1])
    kitty = Path(sys.argv[2]).resolve()
    assert kitty.is_relative_to(REPO / "target") and kitty.is_file(), kitty
    kitten = kitty.with_name("kitten")
    assert kitten.is_file()
    checkpoints = json.loads((root / "kitty-checkpoints.json").read_text())
    assert checkpoints and any(item["visible"] for item in checkpoints)
    assert any(not item["visible"] for item in checkpoints)
    renderer_probe = {"file": "__renderer-probe__", "color": [255, 0, 0], "visible": True}
    checkpoints = ([renderer_probe] if "--renderer-only" in sys.argv[3:]
                   else [renderer_probe, *checkpoints])
    visual = Path(tempfile.mkdtemp(prefix="visual-", dir=root))
    private_home = visual / "home"
    private_home.mkdir()
    allowed = {"PATH", "LANG", "LC_ALL", "LC_CTYPE", "LD_LIBRARY_PATH", "LD_PRELOAD",
               "LIBGL_DRIVERS_PATH", "LIBGL_DEBUG", "GALLIUM_DRIVER",
               "MESA_GL_VERSION_OVERRIDE", "MESA_GLSL_VERSION_OVERRIDE",
               "FONTCONFIG_FILE", "FONTCONFIG_PATH", "XDG_DATA_DIRS", "NO_COLOR"}
    env = {key: value for key, value in os.environ.items() if key in allowed}
    env.update(HOME=str(private_home), XDG_CONFIG_HOME=str(private_home),
               LIBGL_ALWAYS_SOFTWARE="1")
    xserver = terminal = None
    read_fd, write_fd = os.pipe()
    try:
        with (visual / "xvfb.log").open("wb") as log:
            xserver = subprocess.Popen(["Xvfb", "-displayfd", str(write_fd), "-screen", "0",
                                        "1920x900x24", "-nolisten", "tcp"],
                                       pass_fds=(write_fd,), stdout=log, stderr=log, env=env)
        os.close(write_fd)
        write_fd = None
        assert select.select([read_fd], [], [], 10)[0], "private Xvfb startup timed out"
        display_number = os.read(read_fd, 32).decode().strip()
        assert display_number.isdigit(), (visual / "xvfb.log").read_text()
        env["DISPLAY"] = ":" + display_number
        results = []
        for index, checkpoint in enumerate(checkpoints):
            record = (root / checkpoint["file"]).resolve()
            assert record.parent == root
            assert record.name == "__renderer-probe__" or record.is_file()
            title = "luvus-graphics-checkpoint-" + str(index)
            socket = "unix:" + str(visual / (str(index) + ".sock"))
            with (visual / (str(index) + ".log")).open("wb") as log:
                terminal = subprocess.Popen([
                    str(kitty), "--config", "NONE", "--listen-on", socket,
                    "--override", "allow_remote_control=socket-only",
                    "--override", "linux_display_server=x11",
                    "--override", "remember_window_size=no",
                    "--override", "initial_window_width=120c",
                    "--override", "initial_window_height=30c",
                    "--override", "window_padding_width=0",
                    "--override", "shell_integration=disabled",
                    "--override", "enable_audio_bell=no",
                    "--override", "font_size=11",
                    sys.executable, str(Path(__file__).resolve()), "--replay", str(root),
                    record.name, title,
                ], stdin=subprocess.DEVNULL, stdout=log, stderr=log, env=env)
            deadline = time.monotonic() + 12
            while time.monotonic() < deadline:
                assert terminal.poll() is None, (visual / (str(index) + ".log")).read_text()
                receipt = subprocess.run([str(kitten), "@", "--to", socket, "ls"],
                                         env=env, capture_output=True, timeout=5)
                windows = safe_windows(receipt.stdout) if receipt.returncode == 0 else []
                if any(child.get("title") == title for window in windows
                       for tab in window["tabs"] for child in tab["windows"]):
                    (visual / (str(index) + "-windows.json")).write_text(
                        json.dumps(windows, indent=2))
                    break
                time.sleep(0.1)
            else:
                raise AssertionError("Kitty did not consume checkpoint: " + str(record))
            geometry = json.loads((private_home / "geometry.json").read_text())
            assert (geometry["columns"], geometry["rows"]) == (120, 30), geometry
            color = tuple(checkpoint["color"])
            stable = 0
            deadline = time.monotonic() + 4
            while time.monotonic() < deadline:
                shot = ImageGrab.grab(xdisplay=env["DISPLAY"]).convert("RGB")
                pixels = list(getattr(shot, "get_flattened_data", shot.getdata)())
                count = pixels.count(color)
                good = count >= 500 if checkpoint["visible"] else count == 0
                stable = stable + 1 if good else 0
                if stable >= 3:
                    break
                time.sleep(0.1)
            shot.save(visual / (record.stem + ".png"))
            assert stable >= 3, (record.name, checkpoint, count, str(visual))
            for absent in checkpoint.get("absent_colors", []):
                assert pixels.count(tuple(absent)) == 0, (record.name, "unexpected source pixels", absent)
            for comparison in ("less_than", "same_pixels_as"):
                if comparison in checkpoint:
                    previous = next(item["pixels"] for item in results if item["file"] == checkpoint[comparison])
                    assert (0 < count < previous if comparison == "less_than" else count == previous), (record.name, comparison, count, previous)
            if checkpoint["visible"]:
                xs = [i % shot.width for i, pixel in enumerate(pixels) if pixel == color]
                assert min(xs) > 100, "image leaked into the outer sidebar"
            results.append({**checkpoint, "pixels": count, "geometry": geometry})
            print(f"PASS: real Kitty {record.stem}, expected pixels={count}", flush=True)
            stop(terminal)
            terminal = None
        (visual / "results.json").write_text(json.dumps(results, indent=2))
        print(f"Screenshots: {visual}", flush=True)
    finally:
        stop(terminal)
        stop(xserver)
        os.close(read_fd)
        if write_fd is not None:
            os.close(write_fd)


if __name__ == "__main__":
    main()
